export const PROPERTY_LIST_REQUEST = "PROPERTY_LIST_REQUEST";
export const PROPERTY_LIST_SUCCESS = "PROPERTY_LIST_SUCCESS";
export const PROPERTY_LIST_FAIL = "PROPERTY_LIST_FAIL";

export const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS";
export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_CONFIRM_SUCCESS = "PASSWORD_RESET_CONFIRM_SUCCESS";

export const ACTIVATION_FAIL = "ACTIVATION_FAIL";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";
export const REGISTRATION_FAIL = "REGISTRATION_FAIL";
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL";
export const PASSWORD_RESET_FAIL = "PASSWORD_RESET_FAIL";
export const PASSWORD_RESET_CONFIRM_FAIL = "PASSWORD_RESET_CONFIRM_FAIL";
